sudo: required

services:
  - docker

# build the test image
before_install:
  - docker build -t wafa01/react-test -f ./client/Dockerfile.dev ./client

# run the test
script:
  - docker run -e CI=true wafa01/react-test npm test
  ## the -e CI=true is to avoid getting the menu
  ## after running the test,
  ##  if test is ok => exit(0) so travis approves

# build the prod images
after_success:
  - docker build -t wafa01/multi-client ./client
  - docker build -t wafa01/multi-nginx ./nginx
  - docker build -t wafa01/multi-server ./server
  - docker build -t wafa01/multi-worker ./worker


# login into the docker CLI to  put these images in dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wafa01/multi-client
  - docker push wafa01/multi-nginx
  - docker push wafa01/multi-server
  - docker push wafa01/multi-worker


deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-616762547800
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
